### ISSUE TITLE
Implement multi-crop (SwAV, DCv2, DINO, MoCo)

### ISSUE THREAD

**Issue by DonkeyShot21** [vturrisi/solo-learn#154]
and improve SimCLR's implementation

**Comment by DonkeyShot21** [comment]
We should keep in mind that [this repo](https://github.com/facebookresearch/suncet/blob/main/src/data_manager.py) has nice parameters for multicrop on CIFAR

**Comment by nicoboou** [comment]
@vturrisi @DonkeyShot21 hi guys, I'm trying to use multicrop with DINO but it seems that it does not work. My guess is that it is because timm vision_transformer is used here, but contrary to the "classical" DINO implem, it does not automatically interpolate positional embeddings for different image sizes. Do you relate on your side ?
