### ISSUE TITLE
Can I update my pytorch-lightning in solo-learn  to 1.5.1 ? Due to this bug.

### ISSUE THREAD

**Issue by KimSoybean** [vturrisi/solo-learn#195]
https://medium.com/@florian-ernst/finding-why-pytorch-lightning-made-my-training-4x-slower-ae64a4720bd1

**Comment by vturrisi** [comment]
Hey,
I found the title of the medium post super misleading. If you check the [issue that he references](https://github.com/PyTorchLightning/pytorch-lightning/issues/10389) it's a slowdown between epochs. Anyway, we are planning on updating our pytorch lightning versions as well, since other major changes are now available. From previous experience, things may break and you may get flooded by warnings. I'll do the update locally and fix whatever problems there are, but this will take at least a couple of days. If there were no major API changes, you should probably be fine with updating.

**Comment by vturrisi** [comment]
Just tried it out, and there are a couple of fixes that need to be done to update. The new PR will improve stuff on the library, including updating pytorch-lightning's version. I got some decent speedups for a small cifar-10 benchmark.

**Comment by DonkeyShot21** [comment]
This is now fixed in the latest version of solo-learn.
