### ISSUE TITLE
Results of Cifar-100 are linear offline?

### ISSUE THREAD

**Issue by kkokilep** [vturrisi/solo-learn#336]
Thank you for answering my questions and thanks for the great repository!

In the table that you all made for Cifar100 on this repo, is the result shown the performance after offline fine-tuning with a linear layer (standard way done in papers) or the accuracy when doing online linear evaluation?

**Comment by DonkeyShot21** [comment]
For cifar100 we used online evaluation because it worked a bit better than offline. Nonetheless, by tuning the offline evaluation you should be able to obtain the same performance. Methodologically, online and offline evals are exactly the same, because the backbone features are detached before being fed to the linear classifier.
