### ISSUE TITLE
barlowtwins train input question?

### ISSUE THREAD

**Issue by showkeyjar** [vturrisi/solo-learn#58]
I'm very glad to see this amazing project, and found it support balowtwins.
so, I read the code, and got one question:

why use out feats for barlowtwins input?
 
`feats1, feats2 = out["feats"]`

and why use diffent time feats?

**Comment by DonkeyShot21** [comment]
Hi! Thanks for your interest in our project!

Those are the features extracted from the ResNet, they are then processed by the projection head. If you check the `train_step` of the base `BaseModel` you will see that it does the forward pass of the encoder (ResNet) and the classifier (linear layer) and packs everything up in a dict. When `BarlowTwins` calls `super().training_step(...)` the parent returns the dict so that we can use the outputs.

**Comment by showkeyjar** [comment]
thanks for your reply.
what's the different of first view and second view?
I can't find any data process code for view input?

**Comment by vturrisi** [comment]
Hey,

NCropAugmentation ([link](https://github.com/vturrisi/solo-learn/blob/61f55c08e97e28cce5edf1a7dcdf52b309b2272e/solo/utils/contrastive_dataloader.py#L34)) is responsible for applying a pipeline of transformations N times (2 as default or more if supporting multicrop). If you follow `main_contrastive.py`, you will see the functions that we call (that end up calling NCropAugmentation. In short, view 1 and view 2 are different augmented (cropped/color jittered/etc) versions of the image.
